#!/usr/bin/env bash

# ====== Variables =============================

#declare -A gaps
#
#gaps["top"]="8"
#gaps["bottom"]="20"
#gaps["left"]="8"
#gaps["right"]="8"
#gaps["inner"]="8"

ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"dotfiles-bar-spaces-jsx\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config external_bar                all:32:0
yabai -m config top_padding                 12
yabai -m config bottom_padding              12
yabai -m config left_padding                12
yabai -m config right_padding               12
yabai -m config window_gap                  12

yabai -m config mouse_follows_focus         on
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         4
yabai -m config active_window_border_color  0xffb7bdf8
yabai -m config normal_window_border_color  0xff181926

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.95
yabai -m config split_ratio                 0.65

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

# ===== Rules ==================================

yabae -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Settings" app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Spotify" app="^Spotify$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Godot" app="Godot" manage=off
#yabai -m rule --add label="Godot" app="Godot" title="^low res jam$" manage=on

