vim.g.mapleader = " "

vim.opt.exrc = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.guicursor = ""
vim.opt.relativenumber = true
vim.opt.hlsearch = false
vim.opt.hidden = true
vim.opt.errorbells = false
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.nu = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = vim.fn.expand("~/.vim/undodir")
vim.opt.undofile = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.opt.background = "dark"
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.conceallevel = 2
